### ISSUE TITLE
feat: 사진첩 

### ISSUE THREAD

**Issue by GEONU-MOON** [GEONU-MOON/pretzel#5]
## New Features

1. 사진첩 기능 구현

### Todos

- [x] 사진첩 스키마 구현
- [x] 게시물 댓글 crud
- [x] 메인화면에 동적 렌더링
